apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-policies
spec:
  selector:
    matchLabels:
      app: mysql-policies
  template:
    metadata:
      labels:
        app: mysql-policies
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: policies_db
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-policies
spec:
  selector:
    app: mysql-policies
  ports:
    - port: 3306
      targetPort: 3306
